/*
 * MainForm.java
 *
 * Основная форма приложения
 */

package ricoko.arismorf;

/**
 * @author maksimenkov (xupypr@xupypr.com)
 */
public class MainForm extends javax.swing.JFrame {

    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logScrollPane = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        logLabel = new javax.swing.JLabel();
        actionLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        progressLabel = new javax.swing.JLabel();
        action = new javax.swing.JLabel();
        mainMenu = new javax.swing.JMenuBar();
        convAtoMButton = new javax.swing.JMenu();
        separator1 = new javax.swing.JMenu();
        convMtoAButton = new javax.swing.JMenu();
        separator2 = new javax.swing.JMenu();
        helpButton = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Конвертатор: АРИСМО <-> МОРФ");

        logTextArea.setColumns(20);
        logTextArea.setRows(5);
        logScrollPane.setViewportView(logTextArea);

        logLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        logLabel.setText("Журнал :");

        actionLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        actionLabel.setText("Выполняемое действие :");

        progressLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        progressLabel.setText("Прогресс выполнения :");

        action.setText("-");

        mainMenu.setName("MainMenu"); // NOI18N

        convAtoMButton.setText("АРИСМО -> МОРФ");
        mainMenu.add(convAtoMButton);

        separator1.setText("|");
        separator1.setEnabled(false);
        mainMenu.add(separator1);

        convMtoAButton.setText("МОРФ -> АРИСМО");
        mainMenu.add(convMtoAButton);

        separator2.setText("|");
        separator2.setEnabled(false);
        mainMenu.add(separator2);

        helpButton.setText("Помощь");
        mainMenu.add(helpButton);

        setJMenuBar(mainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                    .addComponent(actionLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(action, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                    .addComponent(logLabel, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(action)
                .addGap(18, 18, 18)
                .addComponent(progressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel action;
    private javax.swing.JLabel actionLabel;
    private javax.swing.JMenu convAtoMButton;
    private javax.swing.JMenu convMtoAButton;
    private javax.swing.JMenu helpButton;
    private javax.swing.JLabel logLabel;
    private javax.swing.JScrollPane logScrollPane;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JMenuBar mainMenu;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JMenu separator1;
    private javax.swing.JMenu separator2;
    // End of variables declaration//GEN-END:variables

}
